const data = {
    products:[
        {
            _id:'1',
            name:'Prom Red Dress',
            category:'Dress',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'VIISHOW',
            rating:5.0,
            numReviews:30,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'African Print Shirt Dress',
            category:'Dress',
            image:'/images/p2.jpg',
            price:80,
            countInStock: 0,
            brand:'Maison Chateau Rouge',
            rating:4.6,
            numReviews:20,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:`VIISHOW Women's Summer Off Shoulder  Dress`,
            category:'Dress',
            image:'/images/p3.jpg',
            price:50,
            countInStock: 2,
            brand:'VIISHOW',
            rating:5,
            numReviews:17,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Black Fit Long Sleeve Bodycon Top',
            category:'Top',
            image:'/images/p4.jpg',
            price:40,
            countInStock: 5,
            brand:'VIISHOW',
            rating:4.8,
            numReviews:17,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'InsNova Women Long Sleeve Floral Velvet Dress',
            category:'Dress',
            image:'/images/p5.jpg',
            price:150,
            countInStock: 15,
            brand:'InsNova',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'InsNova Women Off Shoulder Cocktail Dress',
            category:'Dress',
            image:'/images/p6.jpg',
            price:200,
            countInStock: 10,
            brand:'VIISHOW',
            rating:4.9,
            numReviews:15,
            description: 'high quality product',
        },
    ]
}

export default data;